### ISSUE TITLE
Drugbank xml

### ISSUE THREAD

**Issue by oganm** [PavlidisLab/GemmaDE#33]
- Get access to the file
- Document version used
- See license for implications in packaging ([CC](https://creativecommons.org/licenses/by-nc/4.0/), Allows reshare)

@jsicherman sorry to bother you again but did you leave a copy of the raw xml file somewhere in the server?

**Comment by oganm** [comment]
doesn't appear to be used anywhere else in the application. will see if removing it makes sense

**Comment by jsicherman** [comment]
Hi Ogan, yeah sorry - I believe the drugbank xml should be packaged in the main directory in `/home/jordan/Thesis Work`. That being said, I only used it during thesis writing for some pseudo-validation. It should be able to be safely removed.
